#!/bin/bash
# Nginx setup script for sale-photosession-site with telegram-bots-platform
# Run this script on your server after deploying with the platform

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Sale PhotoSession Site - Nginx Setup ===${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root (use sudo)${NC}"
    exit 1
fi

# Get domain name
echo -e "${YELLOW}Enter your domain name (e.g., photos.example.com):${NC}"
read -r DOMAIN

if [ -z "$DOMAIN" ]; then
    echo -e "${RED}Domain name cannot be empty${NC}"
    exit 1
fi

# Get backend port from .env or use default
BACKEND_PORT=$(grep "^BACKEND_PORT=" .env 2>/dev/null | cut -d'=' -f2 || echo "8000")
BOT_DIR=$(pwd)

echo -e "${GREEN}Using configuration:${NC}"
echo "  Backend: 127.0.0.1:$BACKEND_PORT"
echo "  Frontend static files: $BOT_DIR/frontend-dist/"
echo ""

# Create nginx configuration
echo -e "${YELLOW}Creating nginx configuration...${NC}"
cat > /etc/nginx/sites-available/sale-photosession-site << EOF
# Sale PhotoSession Site - Nginx Configuration
# Generated by setup-nginx.sh

upstream backend {
    server 127.0.0.1:$BACKEND_PORT;
}

server {
    listen 80;
    server_name $DOMAIN;

    # Root directory for static files
    root $BOT_DIR/frontend-dist;
    index index.html;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    # Max upload size for image generation
    client_max_body_size 10M;

    # Gzip compression for static files
    gzip on;
    gzip_vary on;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml+rss;

    # Backend API endpoints
    location /api {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;

        # Increase timeouts for image generation
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
        proxy_send_timeout 300s;
    }

    # API Documentation
    location /docs {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /openapi.json {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
    }

    # Health check
    location /health {
        proxy_pass http://backend;
        access_log off;
    }

    # WebSocket for real-time updates
    location /api/generation/ws {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    # Frontend - serve static files with proper caching
    location / {
        try_files \$uri \$uri/ /index.html;

        # Cache static assets
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        # Don't cache index.html
        location = /index.html {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
        }
    }

    # Deny hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Logs
    access_log /var/log/nginx/sale-photosession-site-access.log;
    error_log /var/log/nginx/sale-photosession-site-error.log;
}
EOF

echo -e "${GREEN}✓ Created /etc/nginx/sites-available/sale-photosession-site${NC}"

# Enable site
echo -e "${YELLOW}Enabling site...${NC}"
ln -sf /etc/nginx/sites-available/sale-photosession-site /etc/nginx/sites-enabled/
echo -e "${GREEN}✓ Enabled site${NC}"

# Test nginx configuration
echo -e "${YELLOW}Testing nginx configuration...${NC}"
if nginx -t; then
    echo -e "${GREEN}✓ Nginx configuration is valid${NC}"
else
    echo -e "${RED}✗ Nginx configuration has errors${NC}"
    exit 1
fi

# Reload nginx
echo -e "${YELLOW}Reloading nginx...${NC}"
systemctl reload nginx
echo -e "${GREEN}✓ Nginx reloaded${NC}"

echo ""
echo -e "${GREEN}=== Setup Complete ===${NC}"
echo ""
echo "Your site should now be accessible at:"
echo -e "${GREEN}http://$DOMAIN${NC}"
echo ""
echo "Next steps:"
echo "1. Build frontend: ${YELLOW}cd /opt/telegram-bots-platform/bots/photosession-site && sudo bash app/build-frontend.sh${NC}"
echo "2. Setup SSL with: ${YELLOW}sudo certbot --nginx -d $DOMAIN${NC}"
echo "3. Test frontend: ${YELLOW}curl http://$DOMAIN${NC}"
echo "4. Test backend API: ${YELLOW}curl http://$DOMAIN/api${NC}"
echo "5. View API docs: ${YELLOW}http://$DOMAIN/docs${NC}"
echo ""
echo "Logs:"
echo "  Access: /var/log/nginx/sale-photosession-site-access.log"
echo "  Error: /var/log/nginx/sale-photosession-site-error.log"
echo ""
